### ISSUE TITLE
Question about mapping responses

### ISSUE THREAD

**Issue by dannylane** [moolitayer/awx-client-go#38]
I'm working on a PR for updating the job data that is returned from the awx-client-go library.
I wanted to ask about the pattern where structs like `Job` are in the data and awx packages.
It looks like the data package structs are for deserializing json and then mapped to structs in the awx package.
Would there be any objection to removing one of these and have the deserialized structs returned directly by the library?
If I add properties for deserialization I dont see the value in replicating these fields in the awx package?
Perhaps its an attempt to decouple from the API? and provide more domain logic in the awx package?

**Comment by zgalor** [comment]
Data structures in `data` package are for JSON serialization and deserialization, and are internal.
Where the `awx` package resources are exported and are the client's API.
This model is indeed built to decouple awx server API and the implementation from the client API.
If you wish to update job data, you will have to do it in both places.

**Comment by dannylane** [comment]
Thanks for the fast reply.
If I wanted all the data from the AWX api then I would need to put it all in both places, I understand that.
But wouldn't that defeat the purpose of being isolated form the AWX structure?
Basically what I guess I'm saying is that I _want_ something that is tightly coupled to the API so I can consume all the data, not an abstraction.
Maybe I should stick with a more generic rest client?
